### ISSUE TITLE
Option for CSVs with no header row

### ISSUE THREAD

**Issue by kisielk** [aniav/ynab-csv#65]
The CSVs I get from my bank don't have a header row, they just go straight into transactions.
I can currently still use the tool and just select the columns based on data in the first transaction, but the data itself is never captured so I need to import that transaction manually

**Comment by dpieski** [comment]
Try selecting this:
![image](https://github.com/aniav/ynab-csv/assets/3300522/30d110b3-66ef-4a18-be30-0adb5cfa130e)

**Comment by kisielk** [comment]
That doesn't change the behaviour, it still skips the first transaction.

**Comment by dpieski** [comment]
Gotcha. For some reason that changes the behavior and works for me on a similar file with no headers.

**Comment by aniav** [comment]
Hey @kisielk I checked with an example file like in the video below and it works fine. Can you check again with your file? If the problem persists, feel free to reopen the issue with an example anonymised file so that I can check the problem. Thank you!

https://github.com/aniav/ynab-csv/assets/182546/520eceb6-c54e-4a00-b145-31a8a94608d4
