### ISSUE TITLE
Date conversion for EQBank CSV

### ISSUE THREAD

**Issue by adrabitt** [aniav/ynab-csv#67]
Hello,

My EQbank CSV files  download with the date format of DD MMM YY where the month portion is not numerical. (eg DEC)

is there someway for the YNAB converter to recognize this and convert it to MM/DD/YYYY so that YNAB stops complaining?

Thanks!

**Comment by jenkuntz** [comment]
I literally just opened an EQ bank account this week and found the same thing. I chose the format "DD/MMM/YYYY" on import where it asks you what the date format is, and it recognizes it then. Hope that helps.

**Comment by adrabitt** [comment]
Hi Jen, this is what I have been doing...however, I was just hoping that the YNAB converter could recognize this and convert automatically so we can avoid this step.

**Comment by jenkuntz** [comment]
Gotcha.

**Comment by aniav** [comment]
Hey @adrabitt CSV converter is intentionally not doing any date conversion because it's available in YNAB import. I'm maintaining the tool in a very minimal way while YNAB is adding more banks coverage in their automatic bank connections. I hope you'll get a proper EQbank connection in YNAB itself 🙌
