### ISSUE TITLE
Date Format not working

### ISSUE THREAD

**Issue by joshlars** [aniav/ynab-csv#72]
I have been using this to convert CSV files for YNAB import for a while, but recently when I try to import the files into YNAB they don't recognize the date format and no matter what I choose, it doesn't display correctly.  I have had to go into the file and change the date manually myself to make it work.

**Comment by aniav** [comment]
Hey @joshlars I think you should try to report it to YNAB.

YNAB CSV doesn't change the date format at all, so if it stopped working on YNAB, it's not because of YNAB CSV. There are issues where people are asking to add date formatting into this tool like #10 or #73 but I didn't get to having enough time to work on this. I'll close this ticket in favour of the other ones already opened with more details. Feel free to add the date format you are strugging with to #10. Thank you!
